### ISSUE TITLE
Does lat_syscall support the performance of opening a new file?

### ISSUE THREAD

**Issue by openluopworld** [foss-for-synopsys-dwc-arc-processors/lmbench#1]
Hi, I would like to add a case for 'open_creat'. The code may like this, but could you tell me how to compile for arm64.
```C
void
do_openclose_creat(iter_t iterations, void *cookie)
{
	struct _state *pState = (struct _state*)cookie;
	int	fd;

	while (iterations-- > 0) {
		fd = open(pState->file, O_RDONLY | O_CREAT, S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH);
		if (fd == -1) {
			perror(pState->file);
			return;
		}
		close(fd);
	}
}
```
Thanks.

**Comment by vineetgarc** [comment]
creating the new test case and compiling for arm64 are 2 different things. 
e.g. to build for ARC, we do make OS=arc-snps-linux-uclibc CC=arc-linux-gcc
You can choose the corresponding compiler for arm64

**Comment by openluopworld** [comment]
As for open, will the file be open many times during test if parallel is set to 1?

**Comment by openluopworld** [comment]
As for open, will the file just be opened once during test if parallel is set to 1? If not, is there any way to do? Thanks.

**Comment by openluopworld** [comment]
Ok, it has loops. ^_^
